### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by raakesh** [octommerce/octommerce#1]
Migration and seeding not working with `php arstisan october:up is not working`

**Comment by triasrahman** [comment]
@raakesh Can you share the errors here?

**Comment by raakesh** [comment]
@triasrahman 
The system isn't detecting octommerce plugin

This is what i'm getting when i use `php artisan october:up`

```
$php artisan october:up            
Migrating application and plugins...
System                              
 - Nothing to migrate.              
Backend                             
 - Nothing to migrate.              
Cms                                 
 - Nothing to migrate.              
Flynsarmy.Menu                      
 - Nothing to update.               
Mja.Forms                           
 - Nothing to update.               
Mohsin.Carousel                     
 - Nothing to update.               
NetSTI.SEO                          
 - Nothing to update.               
October.Demo                        
 - Nothing to update.               
October.Test                        
 - Nothing to update.               
RainLab.Blog                        
 - Nothing to update.               
RainLab.Builder                     
 - Nothing to update.               
RainLab.Pages                       
 - Nothing to update.               
RainLab.Twitter                     
 - Nothing to update.               
RainLab.User                        
 - Nothing to update.               
Raviraj.Rjsliders                   
 - Nothing to update. 
```

```
                                `
```

**Comment by surahmans** [comment]
@raakesh
I thought you run `git clone https://github.com/octommerce/octommerce.git` instead `git clone https://github.com/octommerce/octommerce.git octommerce/octommerce` in `plugins` directory. Make sure this plugin in the correct path which is `plugins/octommerce/octommerce`.

**Comment by raakesh** [comment]
Here snapshot of project folder structure 
![folder-structure](https://cloud.githubusercontent.com/assets/2386374/19620578/2a990bb2-989e-11e6-8d47-a4eb56c7adff.png)

**Comment by triasrahman** [comment]
@raakesh Have you installed required plugins? Since it's not published yet on OctoberCMS marketplace, you should install plugin dependencies manually. They are:
- RainLab.User
- RainLab.Location
- Responsiv.Currency
- Responsiv.Pay

I think it can solve your problem :)
Goodluck!

**Comment by raakesh** [comment]
@triasrahman @surahmans 
Thanks. Its working now.
Missed these two plugins
- Responsiv.Currency
- Responsiv.Pay

are there any suggested theme for this ?

**Comment by ghost** [comment]
I have the same problem and I installed all dependencies before, is there a new dependency not listed here that would block the install ?

**Comment by dbrw** [comment]
I think RainLab.Notify is also a dependency

**Comment by triasrahman** [comment]
@dbrw Noted, let me check it.

**Comment by triasrahman** [comment]
@dbrw You will need RainLab.Notify because of RainLab.UserPlus has a dependency on RainLab.Notify. It's actually not required by this plugin.

**Comment by dbrw** [comment]
> @dbrw You will need RainLab.Notify because of RainLab.UserPlus has a dependency on RainLab.Notify. It's actually not required by this plugin.

Noted. Thanks!
