### ISSUE TITLE
error class ProductFilters.php

### ISSUE THREAD

**Issue by juan-amaguana** [octommerce/octommerce#2]
Hello as they are, first thanks for this plugin for October cms the error I found in the class folder in the ProductFilters.php file in the function list. I have a question like I can add the product finder on my page.

Thank you very much .

**Comment by surahmans** [comment]
Hello @juferamax93, what's PHP version are you using for? I think it comes from PHP version. But next time I'll try to rename it to make it work on all version. Thanks.

**Comment by juan-amaguana** [comment]
Hello, how are you thank you for responding, the php version I use is 5.6 go ahead with this plugin, I'm working with it and hope to collaborate with something.

Thank you.
