### ISSUE TITLE
Error Duplicate Column Name 'state_id'

### ISSUE THREAD

**Issue by ryuhiro** [octommerce/octommerce#4]
Hi, i'm trying to install your plugin in my october cms. But, i got these error. Could you tell me how to fix it?
![errors](https://user-images.githubusercontent.com/27657919/38302365-8cf37412-382c-11e8-8557-57aa05204117.jpg)

**Comment by Almusamim** [comment]
I got the same error.

**Comment by Almusamim** [comment]
The issue is that the Responsiv.Pay plugin requires Rainlab.UserPlus which has these same columns so just comment out _state_id, city_id, phone in add_profile_columns_to_users_table.php_ until this is fixed

**Comment by ghost** [comment]
Same here

**Comment by quangtrongonline** [comment]
remove user plus plugin to resovel issue.

**Comment by triasrahman** [comment]
Hi guys, I think this problem is caused by RainLab.UserPlus plugin dependency. I've already fixed it on migration by checking the columns before creating them. Thanks for your feedback!
